[package]
name = "TensorClerum"
version = "0.1.11"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", features = ["serde"] }
rand_distr = "0.5.1"
rand = "0.9.2"
serde = { version = "1", features = ["derive"] }